#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HangmanApp.Resource", IsApplication=true)]

namespace HangmanApp
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int eight_Letter_Words = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int five_Letter_Words = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int four_Letter_Words = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int seven_Letter_Words = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int six_Letter_Words = 2130771972;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int BackGround = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int BackGround2 = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int blank = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int Hang1 = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int Hang2 = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int Hang3 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int Hang4 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int Hang5 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int Hang6 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int Hang7 = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int Hang8 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int Hang9 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int HangManApp = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int icon = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int btn_Account = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int btn_Login = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int btn_MainLogIn = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int btn_NewGame = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int btn_Quit = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int btn_Start = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int edt_Username = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int img_GameBackground = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int img_Hanging = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int img_LoginBackground = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int img_OptionsBackground = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int img_Splash = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int ll_Arow = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int ll_Qrow = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int ll_TopLayout = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int ll_Zrow = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int mainLayout = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int rb_Easy = 2130903057;
			
			// aapt resource value: 0x7F030012
			public const int rb_Hard = 2130903058;
			
			// aapt resource value: 0x7F030013
			public const int rb_Normal = 2130903059;
			
			// aapt resource value: 0x7F030014
			public const int rb_OptionEasy = 2130903060;
			
			// aapt resource value: 0x7F030015
			public const int rb_OptionHard = 2130903061;
			
			// aapt resource value: 0x7F030016
			public const int rb_OptionNormal = 2130903062;
			
			// aapt resource value: 0x7F030017
			public const int rg_Difficulty = 2130903063;
			
			// aapt resource value: 0x7F030018
			public const int rg_OptionsDifficulty = 2130903064;
			
			// aapt resource value: 0x7F030019
			public const int txt_ChanceDisplay = 2130903065;
			
			// aapt resource value: 0x7F03001A
			public const int txt_DifficultyPrompt = 2130903066;
			
			// aapt resource value: 0x7F03001B
			public const int txt_HighScore = 2130903067;
			
			// aapt resource value: 0x7F03001C
			public const int txt_LoginWelcome = 2130903068;
			
			// aapt resource value: 0x7F03001D
			public const int txt_OptionDifficulty = 2130903069;
			
			// aapt resource value: 0x7F03001E
			public const int txt_OptionsWelcome = 2130903070;
			
			// aapt resource value: 0x7F03001F
			public const int txt_ScoreDisplay = 2130903071;
			
			// aapt resource value: 0x7F030020
			public const int txt_UsernamePrompt = 2130903072;
			
			// aapt resource value: 0x7F030021
			public const int txt_Welcome = 2130903073;
			
			// aapt resource value: 0x7F030022
			public const int txt_WordDisplay = 2130903074;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Game = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Login = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int Options = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int Hello = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
